---
title: 'Aluguel de casas: fazendo predições sobre o valor de aluguel decasas.'
output:
  pdf_document: default
  html_notebook: default

---

# Importação dos dados
```{r, eval=TRUE}
setwd("D:\\07 04 2020\\Documents\\Edgar\\Projetos\\Data_sciece\\DataScience_projects\\Vendas_casa")
library("tidyverse")

dados<- read.csv("houses_to_rent.csv", header = T)
ndados<-nrow(dados) 
View(dados)
```

# Limpeza e Preparação dos dados

```{r}
mineirados<- dados%>%select(-(hoa:total))

hoa<- dados%>% select(hoa)%>%
  str_replace_all(",",".")%>% str_remove_all("[R&$]")


```

Os dados são separados em treino e teste, sendo 80% para treinar o modelo e 20%
para treinar.
```{r}
n_treino<- (70/100)*ndados
set.seed(100)
ua<- sample(n_treino)
treino<- dados[ua,]; View(treino)
teste<- dados[-ua,]; View(teste)

```


# Treinamento do modelo
```{r}

model<- lm(total~.,data= treino)
View(predict(model, teste))

```

# Avaliação da performance do modelo
```{r}
predito<-predict(model2,teste)
per<- teste %>% select("id", "price")%>%
  mutate(predito) %>% mutate(erro= price-predito )%>%
  mutate(erro_abs= abs(erro))%>%mutate(erro_perc= erro/price)%>% mutate(erro_percabs= abs(erro_perc))
View(per)

# Calculando o erro medio absoluto e percentual medio
erro_medio<- mean(per$erro_abs); erro_medio
erro_percmed<- mean(per$erro_percabs); erro_percmed
summary(per$erro_percabs)

# Calculando o coeficiente de determinacao
rsquad<- summary(model)
rsquad$adj.r.squared
```





